### ISSUE TITLE
Speed up ethernet / wifi comms

### ISSUE THREAD

**Issue by chrisflesher** [jfjlaros/arduino-simple-rpc#16]
WiFi remote procedure calls were running very slowly. The root cause is that the `serial_for_url` has a 0.3 second sleep in its `close` function (in `pyserial` `protocol_socket.py` file). This ensures each remote procedure call will take longer than 0.3 seconds when using `simple_rpc.SocketInterface`. Using the `simple_rpc.SerialInterface` does not have this delay for ethernet or wifi connections but using this interface prevents the microcontroller from doing other things besides communicating in the main loop.

Some ideas for workarounds:
- Request the offending `sleep` call from the pyserial library be removed
- Use mock.patch to bypass sleep (hack)
- Reimplement the `SocketInterface` class to use a `socket` instead of `serial.serial_for_url`
- Use a `SerialInterface` for everything and make it the responsibility of the Arduino to periodically exit and do other things

**Comment by jfjlaros** [comment]
I would go for the first option and perhaps implement the second while we wait for a reply.

**Comment by jfjlaros** [comment]
Something like this [patch](https://gist.github.com/jfjlaros/3aa578dab8d78597613235c5bafe6565) seems to work (just do an `import patch`).

**Comment by chrisflesher** [comment]
Yes, that worked! I will just use this hack for my project files until we get a response from pyserial.
