### ISSUE TITLE
Initialize interface from disk

### ISSUE THREAD

**Issue by chrisflesher** [jfjlaros/arduino-simple-rpc#18]
I'm trying to use simple_rpc interface over an RF link. It is a very slow procedure to load the interface definition (e.g. 2 min to load 29 function definitions). I was wondering if it might be possible to cache the interface definition to disk and re-use it (assuming it doesn't change).

**Comment by jfjlaros** [comment]
That should not be too hard, but I wonder why this link is so slow. Are you working with a LoRaWAN or something like that?

**Comment by chrisflesher** [comment]
Yes, using the RadioHead RF95 library (LoRaWAN).

**Comment by chrisflesher** [comment]
We would like to be able to load it straight from disk rather than loading it the long way the first time and caching it (to avoid watchdog timeout).

**Comment by jfjlaros** [comment]
That sounds interesting. I would be happy to lean about the actual use case.

I will draft a design and share it with you tomorrow, it is getting rather late here.

**Comment by chrisflesher** [comment]
Thanks! It is for an ice penetrating probe experiment. We have a cryochamber that simulates the surface of Europa (a moon of Jupiter). The chamber is about 1m diameter and filled with 2m of ice / 1m of vacuum. We putting a small probe in there (about 3cm diameter by 10cm tall copper slug with electronics inside) and drilling down. 

We're using 900MHz RF LoRa link to communicate because it works well even when there is water (unlike 2.4GHz wifi). Once the probe enters the ice we expect particles to seal the entrance and we'll start to pressurize the cavity enough to make water, heat it up, and pump it. We'll see what happens!

**Comment by chrisflesher** [comment]
For comms we have a simple serial to RF95 Arduino on the surface. Then in the ice is an Arduino with RF95 wrapped by a Stream class so we can use the simple rpc interface. There were some issues getting this to work, we found we had to buffer characters coming over RF95 until no new data was seen for 200ms. This was needed for the simple rpc interface to get the full message.

**Comment by chrisflesher** [comment]
It is working great, it is slow (e.g. 3 seconds per RPC call) but that's fine since we're melting ice :)

**Comment by jfjlaros** [comment]
I have something working in the [files](https://github.com/jfjlaros/arduino-simple-rpc/tree/files) branch.

Tests and documentation is missing and I want to do a bit of refactoring, but I think it is good for testing purposes.

**Comment by chrisflesher** [comment]
Ok, thank you! I'll get a chance to test it either Monday or Wednesday of
next week.

**Comment by chrisflesher** [comment]
I tried the `files` branch and it worked well. Thanks for writing this.

**Comment by jfjlaros** [comment]
I just merged the branch and released a new version.
