### ISSUE TITLE
Ethernet support

### ISSUE THREAD

**Issue by chrisflesher** [jfjlaros/arduino-simple-rpc#2]
It would be nice to add ethernet support.

**Comment by jfjlaros** [comment]
Agreed, this was the reason for making the plugin system.

Unfortunately, I do not have an ethernet shield, so I have no way of testing any of this. I assume that the ethernet plugin in simpleRPC is not functional at the moment.

**Comment by chrisflesher** [comment]
Maybe I'll take a shot at this, I have a couple of different ethernet
devices (RJ45 and WiFi)

**Comment by jfjlaros** [comment]
Sounds good.
