### ISSUE TITLE
Type hinting correction on *args and **kwargs in function definitions

### ISSUE THREAD

**Issue by FourFUN** [jfjlaros/arduino-simple-rpc#22]
**Describe the bug**
Type hinting for `*args` and `**kwargs` in function definitions need to specify the type of the element contained, rather than the type of the `*args` and `**kwargs`. See this stackoverflow post: https://stackoverflow.com/questions/37031928/type-annotations-for-args-and-kwargs and the referenced PEP

**To Reproduce**
Run static type checker (e.g mypy/pylance/etc.) on code when calling e.g, call_method(str, bytes) and notice reported error.

**Expected behavior**
`*args` and `**kwargs` fields should be type hinted with the type of at least one of the contents. In the case of this project, at least for `call_mehtod()` I presume `*args` should be type hinted with `Any`, or maybe `Union(bytes, int, float, "rest-of-simpleRPC-types")`
Example of change
```
From:
def call_method(self: object, name: str, *args: list) -> Any:
To:
def call_method(self: object, name: str, *args: Any) -> Any:
````

**Comment by gpantazis** [comment]
I believe it does. Sorry for the delayed response on my end. As always you are awesome in how fast you respond and the great work overall!
