### ISSUE TITLE
Module hangs on _get_methods()

### ISSUE THREAD

**Issue by RStarik** [jfjlaros/arduino-simple-rpc#3]
**Module hangs on _get_methods()**
I have Arduino UNO R3 with HDC1080 sensor, code:
```
#include <simpleRPC.h>
#include <Wire.h>
#include "ClosedCube_HDC1080.h"


HardwareSerialIO io;
ClosedCube_HDC1080 hdc1080;

double readTemperature(void) {
  return hdc1080.readTemperature();
}

double readHumidity(void) {
  return hdc1080.readHumidity();
}

void setup(void) {
  Serial.begin(9600);
  io.begin(Serial);
  hdc1080.begin(0x40);
}

void loop(void) {
  interface(
    io,
    readTemperature, F("readTemperature: Read temperature from hdc1080 sensor. @return: double."),
    readHumidity, F("readHumidity: Read humidity from hdc1080 sensor. @return: double."));
}
```

Module hangs when I trying to get instance of interface('/dev/ttyACM0'). When I pressed **Ctrl** + **C**:
```
>>> from simple_rpc import Interface
>>> interface = Interface('/dev/ttyACM0')
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stark/tmp/arduino/venv/lib/python3.8/site-packages/simple_rpc/simple_rpc.py", line 37, in __init__
    self.open()
  File "/home/stark/tmp/arduino/venv/lib/python3.8/site-packages/simple_rpc/simple_rpc.py", line 117, in open
    self.methods = self._get_methods()
  File "/home/stark/tmp/arduino/venv/lib/python3.8/site-packages/simple_rpc/simple_rpc.py", line 81, in _get_methods
    if self._read_byte_string() != _protocol:
  File "/home/stark/tmp/arduino/venv/lib/python3.8/site-packages/simple_rpc/simple_rpc.py", line 62, in _read_byte_string
    return read_byte_string(self._connection)
  File "/home/stark/tmp/arduino/venv/lib/python3.8/site-packages/simple_rpc/io.py", line 98, in read_byte_string
    return _read_bytes_until(stream, _end_of_string)
  File "/home/stark/tmp/arduino/venv/lib/python3.8/site-packages/simple_rpc/io.py", line 18, in _read_bytes_until
    char = stream.read(1)
  File "/home/stark/tmp/arduino/venv/lib/python3.8/site-packages/serial/serialposix.py", line 565, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
KeyboardInterrupt
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Open python console
2. Import Interface from simple_rpc
3. Create Interface instance
4. It hangs

**Expected behavior**
It creates interface instance

**Screenshots**
![Screenshot from 2020-11-27 09-53-59](https://user-images.githubusercontent.com/17502269/100420177-06f75700-3097-11eb-8ce2-0f0470119712.png)
![photo_2020-11-27_09-57-23](https://user-images.githubusercontent.com/17502269/100420207-14144600-3097-11eb-8544-7ef6d4a016c8.jpg)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - [simpleRPC](https://github.com/jfjlaros/simpleRPC) 3.1.0
 - Python 3.8.6
 - arduino-simple-rpc==2.0.1
 - configparser==5.0.1
 - pyserial==3.5

**Additional context**
I get interface instance if I try again after Ctrl + C

**Comment by jfjlaros** [comment]
This may have something to do with this [issue](https://github.com/jfjlaros/simpleRPC/issues/1). Could you try to set an initialisation [delay](https://arduino-simple-rpc.readthedocs.io/en/latest/library.html#library)? E.g.,

    interface = Interface('/dev/ttyACM0', wait=2)

**Comment by RStarik** [comment]
Oh, thanks, it works
